\\Practice Questions



SELECT FIRST_NAME, SALARY
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY + 10000 AS FUTURE_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;