CREATE TABLE EMPLOYEES (
EMPLOYEE_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
SALARY NUMBER(8,2),
DEPARTMENT_ID NUMBER
);

INSERT INTO EMPLOYEES VALUES (101,'Baskar','Raja',25000,10);
INSERT INTO EMPLOYEES VALUES (102,'Arun','Kumar',30000,20);
INSERT INTO EMPLOYEES VALUES (103,'Priya','Devi',28000,10);
INSERT INTO EMPLOYEES VALUES (104,'Rahul','Sharma',35000,30);
INSERT INTO EMPLOYEES VALUES (105,'Kavin','Raj',22000,20);

COMMIT;

SELECT *
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES;

SELECT EMPLOYEE_ID AS EMP_NO, 
FIRST_NAME AS NAME, SALARY AS PAY
FROM EMPLOYEES;

SELECT FIRST_NAME,
SALARY, SALARY + 5000 AS NEW_SALARY
FROM EMPLOYEES;

SELECT FIRST_NAME,
SALARY,
SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES;











