SELECT DEPARTMENT_ID 
FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES;

INSERT INTO EMPLOYEES
VALUES (106,'Arun','Singh',32000,20);

SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY > 25000;

\\Lesson 2.1 — Comparison Operators

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

COMMIT;



