SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE SALARY > 30000
OR DEPARTMENT_ID = 20 AND SALARY < 25000;

INSERT INTO EMPLOYEES
VALUES (107,'Ajay','Kumar',27000,10);

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n%';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n';

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a%';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,30);

SELECT FIRST_NAME, EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY IN (22000,25000);

INSERT INTO EMPLOYEES
VALUES (108,'Vijay','Kumar',26000,NULL);

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

SELECT FIRST_NAME, EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
AND (SALARY BETWEEN 25000 AND 30000)
AND FIRST_NAME LIKE 'B%';

SELECT FIRST_NAME AS NAME
FROM EMPLOYEES;

\\Tomorrow has been complete recall section\\ 



